---
  - name: Reload the NGINX service
    ansible.builtin.systemd:
      name: nginx
      state: reloaded
      enabled: yes
    become: yes

  - name: Update service configuration
    shell: systemctl daemon-reload
    become: yes

  - name: Restart the Newsletter service
    service:
      name: newsletter
      state: restarted
      enabled: yes
    become: yes

  - name: Restart the Knowledge Map service
    service:
      name: knowledge-map
      state: restarted
      enabled: yes
    become: yes

  - name: Restart the Agile CLI Files service
    service:
      name: agile-cli-files
      state: restarted
      enabled: yes
    become: yes

  - name: Restart the OpenVPN service
    service:
      name: openvpn
      state: restarted
      enabled: yes
    become: yes
