---

user: vagrant
home_bin: /home/vagrant/bin

github_user: ant1k9
github_token:

dropbox_refresh_token:
dropbox_credentials:

taskd_source_dir: ~/taskd-1.1.0
taskd_user: ant1k9

blogs_bot_token:
blogs_channel:

openvpn_server_name: my-openvpn
openvpn_ca_password: my-password
openvpn_path_easyrsa: /usr/share/easy-rsa
openvpn_client_name: client1
openvpn_client_password: my-password
