---

user: vagrant
home_bin: /home/{{ user }}/bin
brew_bin: /home/linuxbrew/.linuxbrew/bin
cargo_bin: /home/{{ user }}/.cargo/bin

github_user: ant1k9
github_token:

taskd_source_dir: ~/taskd-1.1.0
taskd_user: ant1k9
