---
  # tasks/main.yml: Main tasks for LocalEnvironment.Ansible

  - include: brew.yml
    when: ansible_distribution | lower == "macos"

  - include: go.yml
  - include: rust.yml
  - include: python.yml
  - include: custom.yml
  - include: misc.yml
  - include: config.yml
