---
  # tasks/main.yml: Main tasks for LocalEnvironment.Ansible

  - include: brew.yml
    when: '"macos" in ansible_distribution | lower'

  - include: go.yml
  - include: rust.yml
  - include: python.yml
  - include: custom.yml
  - include: misc.yml
  - include: config.yml
