---

  - name: Install misc packages
    shell:
      cmd: |
        mkdir -p {{ home_bin }}
        mkdir -p ~/.config/fish/completions

        # misc
        mkdir -p $HOME/ny2j/projects/misc
        git clone https://github.com/ant1k9/misc $HOME/ny2j/projects/misc
        cd $HOME/ny2j/projects/misc
        ./install.fish misc
        for package in \
          knowledge-map \
          agile-cli \
          auto-launcher \
          pg-analyze \
          repeat \
          noter \
          aliasme \
          formatter \
          noter \
          daily-dashboard; do
          misc install "$package"
        done

    ignore_errors: true
    tags:
      - misc
