---

  - name: Install Cargo and Rustc
    shell:
      cmd: rustup-init -y

  - name: Install Cargo crates
    shell:
      cmd: "cargo install {{ item }}"
    with_items:
      - cargo-add
      - choose
      - du-dust
      - htmlq
      - svgbob_cli
      - tealdeer
      - tokei
    ignore_errors: true
    tags:
      - rust
