---
# tasks/nginx.yml: Nginx management tasks for RocketChat.Ansible

  - name: Ensure Nginx is present
    package: name=nginx state=present

  - name: Deploy Nginx configuration
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
    with_items:
      - { src: nginx.conf.j2, dest: /etc/nginx/nginx.conf }
      - { src: rocket_chat.conf.j2, dest: /etc/nginx/conf.d/rocket_chat.conf }
    notify: Reload the Nginx service

  - name: Ensure the PFS key has been generated (this can take a while!)
    shell: >-
      openssl dhparam -out {{ rocket_chat_nginx_pfs_key_path }}
      {{ rocket_chat_nginx_pfs_key_numbits }}
    when: rocket_chat_nginx_generate_pfs_key|bool
    args:
      creates: "{{ rocket_chat_nginx_pfs_key_path }}"
    notify: Reload the Nginx service

  - name: Ensure the Nginx service is running/enabled
    service: name=nginx state=started enabled=true
