---

  - name: Install packages
    apt:
      state: present
      update_cache: yes
      pkg:
        - curl
        - fish
        - git
        - golang
        - jq
        - make
        - python
        - python3-pip
        - sqlite3
        - unzip
        - vim
    become: yes

  - name: Install python packages
    shell: |
      pip install "{{ item }}"
    with_items:
      - litecli
      - flask
      - uploadserver

  - name: Clone repos
    ansible.builtin.git:
      repo: "{{ item }}"
      dest: "{{ item | regex_replace('^.*/(.*)$', '\\1') }}"
    with_items:
      - https://github.com/ant1k9/misc
      - https://github.com/ant1k9/blog-notifier

  - name: Create bin directory for user
    file:
      dest: {{ home_bin }}
      state: directory

  - name: Add bin to path
    shell: |
      test -z "$(grep '{{ home_bin }}' ~/.bashrc)" &&
        echo -e "export PATH=$PATH:{{ home_bin }}\nexport EDITOR=vim" >> ~/.bashrc
      test -z "$(grep '{{ home_bin }}' ~/.config/fish/config.fish)" &&
        echo -e "export PATH=$PATH:{{ home_bin }}\nexport EDITOR=vim" >> ~/.config/fish/config.fish
    ignore_errors: yes
