---
  # tasks/main.yml: Main tasks for PersonalServer.Ansible

  - include: init.yml
    tags: init

  - include: misc.yml
    tags: misc

  - include: nginx.yml
    tags: misc

  - include: blogs-notifier.yml
    tags: blogs-notifier

  - include: taskfile.yml
    tags: taskfile

  - include: taskd.yml
    tags: taskd

  - include: taskd-client.yml
    tags: taskd

  - include: openvpn.yml
    tags: openvpn

  - include: chezmoi.yml
    tags: chezmoi.yml
