---
  # tasks/main.yml: Main tasks for PersonalServer.Ansible

  - include: init.yml
    tags: init

  - include: taskfile.yml
    tags: taskfile

  - include: misc.yml
    tags: misc

  - include: nginx.yml
    tags: misc

  - include: blogs-notifier.yml
    tags: blogs-notifier

  - include: knowledge-map.yml
    tags: blogs-notifier

  - include: blogs-notifier-entertainment.yml
    tags: blogs-notifier

  - include: chezmoi.yml
    tags: chezmoi.yml

  - include: openvpn-server.yml
    tags: openvpn

  - include: openvpn-client.yml
    tags: openvpn

  - include: api-crawler.yml
    tags: api-crawler
