---
# tasks/main.yml: Main tasks for PersonalServer.Ansible

  - name: Install packages
    apt:
      name: "{{ item }}"
      update_cache: yes
      state: present
    with_items:
      - git
      - fish
      - golang
      - python
      - sqlite3
      - vim
      - python3-pip
      - make
    become: yes

  - name: Install python packages
    shell: |
      pip install "{{ item }}"
    with_items:
      - litecli
      - flask

  - name: Clone repos
    ansible.builtin.git:
      repo: "{{ item }}"
      dest: "{{ item | regex_replace('^.*/(.*)$', '\\1') }}"
    with_items:
      - https://github.com/ant1k9/deposit-watcher
      - https://github.com/ant1k9/misc
      - https://github.com/ant1k9/blog-notifier

  - name: Create bin directory for user
    file:
      dest: {{ home_bin }}
      state: directory

  - name: Add bin to path
    shell: |
      test -z "$(grep '{{ home_bin }}' ~/.bashrc)" &&
        echo "export PATH=$PATH:{{ home_bin }}" >> ~/.bashrc
      test -z "$(grep '{{ home_bin }}' ~/.config/fish/config.fish)" &&
        echo "export PATH=$PATH:{{ home_bin }}" >> ~/.config/fish/config.fish
    ignore_errors: yes

  - name: Install rotate-backups
    shell:
      cmd: make rotate-backups && mv deposit-rotate-backups {{ home_bin }}/rotate-backups
      chdir: deposit-watcher

  - include: misc.yml
    tags: misc

  - include: blogs-notifier.yml
    tags: blogs-notifier

  - include: taskfile.yml
    tags: taskfile

  - include: taskd.yml
    tags: taskd

  - include: openvpn.yml
    tags: openvpn
