---

  - name: Install misc utilties
    shell:
      cmd: |
        mkdir -p ~/.config/fish/completions
        ./install.fish misc
        ./install.fish dropbox
        ./install.fish newsletter
      chdir: misc

  - name: Install additional utilities
    shell:
      cmd: |
        GOBIN={{ home_bin }} go get github.com/ericchiang/pup
        GOBIN={{ home_bin }} go get github.com/ant1k9/deposit-watcher/cmd/rotate-backups

  - name: Download the latest links db dump
    shell:
      cmd: |
        ~/bin/gotask -t ~/.config/task/Taskfile.yml update-token
        DUMP_FILE=$( \
          curl -X POST https://api.dropboxapi.com/2/files/list_folder \
            -H "Authorization: Bearer $(cat /tmp/token)" \
            -H "Content-Type: application/json" \
            -d '{"path": "/links"}' \
            | jq '.entries | last | .path_lower' | tr -d '"'
        )
        curl -X POST https://content.dropboxapi.com/2/files/download \
          -H "Authorization: Bearer $(cat /tmp/token)" \
          -H "Dropbox-API-Arg: {\"path\": \"$DUMP_FILE\"}" \
          -o /tmp/links.db.zip

  - name: Extract links.db archive
    ansible.builtin.unarchive:
      src: /tmp/links.db.zip
      dest: ~/misc/newsletter/
      remote_src: yes

  - name: Deploy the Newsletter App service file
    template:
      src: templates/newsletter-app.service
      dest: /etc/systemd/system/newsletter.service
    notify:
      - Update service configuration
      - Restart the Newsletter service
    become: yes

  - name: Set crons for newsletter
    ansible.builtin.cron:
      name: "newsletter send"
      minute: "15,45"
      hour: "6-20"
      job: "cd /home/{{ user }}/misc/newsletter && TELEGRAM_CHANNEL={{ newsletter_channel }} TELEGRAM__BOT_TOKEN={{ telegram_bot_token }} ./generate.fish send"
