---

  - name: Install go-task/task
    shell:
      cmd: |
        sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d
        mv ~/bin/task ~/bin/gotask

  - name: Set crons for gotask
    ansible.builtin.cron:
      name: "check dirs"
      minute: "20"
      hour: "19"
      job: "{{ home_bin }}/gotask -t ~/.config/task/Taskfile.yml load-cloud-data &>> /tmp/log.err"

  - name: Get private Taskfile.yml
    ansible.builtin.git:
      repo: https://{{ github_user }}:{{ github_token }}@github.com/{{ github_user }}/go-task-config
      dest: "~/.config/task"

  - name: Prepare .env for taskfile
    ansible.builtin.template:
      src: templates/taskfile.env
      dest: "~/.config/task/.env"
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: "0644"

  - name: Update user in the Taskfile.yml
    shell:
      cmd: sed -i 's:antik:{{ user }}:g' ~/.config/task/Taskfile.yml
