---
  - name: Install packages
    apt:
      state: present
      update_cache: yes
      pkg:
        - g++
        - libgnutls28-dev
        - uuid-dev
        - cmake
        - gnutls-bin
        - taskwarrior
    become: yes

  - name: Download taskd tarball
    get_url:
      url: https://taskwarrior.org/download/taskd-1.1.0.tar.gz
      dest: ~/taskd-1.1.0.tar.gz

  - name: Extract taskd archive
    ansible.builtin.unarchive:
      src: ~/taskd-1.1.0.tar.gz
      dest: ~/
      remote_src: yes

  - name: Build taskd executable
    shell:
      cmd: |
        cmake -DCMAKE_BUILD_TYPE=release .
        make
        sudo make install
      chdir: {{ taskd_source_dir }}

  - name: Initialize taskd directory
    file:
      dest: "$TASKDDATA"
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"
    become: yes

  - name: Initiazlie taskd server
    shell:
      cmd: taskd init

  - name: Update taskd config
    template:
      src: templates/taskd.config
      dest: "$TASKDDATA/config"

  - name: Generate ceritificates for the server
    shell:
      cmd: |
        ./generate
        cp *.pem "$TASKDDATA"
        taskd config --force client.cert $TASKDDATA/client.cert.pem
        taskd config --force client.key $TASKDDATA/client.key.pem
        taskd config --force server.cert $TASKDDATA/server.cert.pem
        taskd config --force server.key $TASKDDATA/server.key.pem
        taskd config --force server.crl $TASKDDATA/server.crl.pem
        taskd config --force ca.cert $TASKDDATA/ca.cert.pem
      chdir: "{{ taskd_source_dir }}/pki"
    notify: Start taskd server
